In [1]:
import numpy as np

In [3]:
print('hello')

hello


In [4]:
1+1

2

In [5]:
numbers = [1,2,3]
print(numbers)

[1, 2, 3]


In [6]:
doubled = []
for num in numbers:
    doubled.append(num*2)
print(doubled)

[2, 4, 6]


In [8]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [12]:
# print(arr*2)
arr_doubled = arr*2
print(arr_doubled)

[2 4 6]


In [11]:
# why the square brackets?

In [13]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
my_list = [2,6,9,12]
my_arr = np.array(my_list)
print(my_list)
print(my_arr)

[2, 6, 9, 12]
[ 2  6  9 12]


In [18]:
data = [44, 8, 32, 45, 37, 42, 47, 26, 31, 11]

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

32.3
34.5
13.1
171.61


In [19]:
nested = [
    [1,2,3],
    [4,5,6],
]
print(nested[0][0])

1


In [20]:
ndarray = np.array([
    [1,2,3],
    [4,5,6]
])
print(ndarray[0,0])

1
