In [1]:
import numpy as np

In [5]:
# 3.1 1D NumPy Arrays
listy = [20,27,9,12,31,17,4,50,39,35]
numplist = np.array(listy)

In [7]:
print(numplist * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [12]:
print(np.mean(numplist))

24.4


In [13]:
print(np.median(numplist))

23.5


In [14]:
print(np.std(numplist))

13.828955130450023


In [15]:
print(np.argmin(numplist))

6


In [16]:
print(np.argmax(numplist))

7


In [17]:
print(numplist[6])
print(numplist[7])

4
50


In [18]:
print(np.min(numplist))
print(np.max(numplist))

4
50


In [20]:
newarr = numplist > 20
print(numplist[newarr])

[27 31 50 39 35]


In [21]:
# 3.2 2D NumPy Arrays
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]

In [23]:
print(np.shape(matrix))
#3 rows, 4 columns

(3, 4)


In [31]:
print([row[2] for row in matrix])

[17, 14, 19]


In [32]:
print(matrix[1])

[8, 21, 14, 3]


In [35]:
newm = [[x * 2 for x in row]for row in matrix]
print(newm)

[[10, 24, 34, 18], [16, 42, 28, 6], [12, 26, 38, 22]]


In [40]:
meanz = [[float(np.mean(row))] for row in matrix]
print(meanz)

[[10.75], [11.5], [12.25]]


In [42]:
ovrmean = np.mean(matrix)
print(ovrmean)

11.5


In [46]:
for row in matrix:
    print('min = ',min(row))
    print('max =',max(row))

min =  5
max = 17
min =  3
max = 21
min =  6
max = 19


In [56]:
arm = np.array(matrix)
flats = arm.flatten()
print(flats)
#compresses all nested rows into a single list

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [59]:
flmin = print(np.argmin(flats))
flmax = print(np.argmax(flats))

7
5


In [70]:
print(np.unravel_index(7, arm.shape))

(np.int64(1), np.int64(3))


In [71]:
matarr = arm > 15
print(arm[matarr])

[17 21 19]


In [76]:
sorty = np.array([np.sort(row) for row in arm])
print(sorty)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [84]:
#4 Prime Star Systems
star = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def prime(star):
    for row in star:
        if row < 2:
            return False
        if row == 2:
            return True
        if row % 2 == 0:
            return False
        for rows in range(3, int(row ** .5) + 1, 2):
            if row % rows == 0:
                return False
            return True
primes = np.array([j for j in star if prime(j)])
print(primes)

[[ 2  3  5]
 [11 13 17]]


In [122]:
#5 Lets play checkers!
#5.1
ze = np.zeros((8, 8))

In [123]:
#5.2
ze[::2, ::2] += 1
print(ze)
#5.3
ze[1::2, 1::2] += 1
print(ze)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [108]:
#5.4
zeb = np.zeros((8,8))
zeb[1::2, ::2] += 1
zeb[::2, 1::2] += 1
print(ze)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [128]:
#6 the expanding universe
def spaces(string, num):
    space = ' ' * num
    return space.join(string)

print(spaces('galxy', 3))

g   a   l   x   y


In [130]:
#7 second brightest star
np.random.seed(20)
starts = np.random.randint(500, 2000, (5, 5))
print(starts)

[[1879  974  771 1747 1424]
 [1742  893 1928 1686 1492]
 [1642 1052 1993  974 1263]
 [1479 1265 1242 1714 1668]
 [1117 1275  985 1779 1494]]


In [148]:
def secondb(starts):
    seconds = []
    for row in range(starts.shape[0]):
        ord = np.sort(starts[row])[::-1]
        seconds.append(ord.item(1))
    return seconds
print(secondb(starts))

[1747, 1742, 1642, 1668, 1494]
